create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key check (key in ('service_schedule', 'announcement')),
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.sms_drafts (
  id bigint generated by default as identity primary key,
  audience text not null check (audience in ('all', 'leaders', 'new', 'custom')),
  message text not null check (char_length(message) between 1 and 320),
  status text not null default 'draft' check (status in ('draft', 'queued', 'sent', 'failed')),
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
alter table public.site_settings enable row level security;
alter table public.sms_drafts enable row level security;

create or replace function public.is_yam_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_yam_admin() from public;
grant execute on function public.is_yam_admin() to authenticated;

create policy "Admins can verify their membership"
on public.admin_users for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Public site settings are readable"
on public.site_settings for select
to anon, authenticated
using (true);

create policy "Admins can insert site settings"
on public.site_settings for insert
to authenticated
with check ((select public.is_yam_admin()));

create policy "Admins can update site settings"
on public.site_settings for update
to authenticated
using ((select public.is_yam_admin()))
with check ((select public.is_yam_admin()));

create policy "Admins can delete site settings"
on public.site_settings for delete
to authenticated
using ((select public.is_yam_admin()));

create policy "Admins can manage SMS drafts"
on public.sms_drafts for all
to authenticated
using ((select public.is_yam_admin()))
with check ((select public.is_yam_admin()));

revoke all on public.admin_users from anon, authenticated;
revoke all on public.site_settings from anon, authenticated;
revoke all on public.sms_drafts from anon, authenticated;

grant select (key, value, updated_at) on public.site_settings to anon, authenticated;
grant insert, update, delete on public.site_settings to authenticated;
grant select (user_id) on public.admin_users to authenticated;
grant select, insert, update, delete on public.sms_drafts to authenticated;
grant usage, select on sequence public.sms_drafts_id_seq to authenticated;

insert into public.site_settings (key, value)
values
  ('service_schedule', '{"day":"Sunday","time":"06:30","timezone":"Atlantic/Reykjavik"}'::jsonb),
  ('announcement', '{"text":"","enabled":false}'::jsonb)
on conflict (key) do nothing;
